name: "Multi event pipeline / workflow"
on: 
    push: #Event: Whenever a push is made to the repository on the master/test  branch
        branches:
            - master
            - test
    pull_request: # Events: Whenever a pull request is made to the repository        
        branches:
            - master
        types:
            - closed
            - opened
    workflow_dispatch:        
 


jobs:
    on-push: # job 1
        if: github.event_name == 'push'
        runs-on: ubuntu-latest
        steps: # steps to be executed in the job
            - name: "Running on master push" # step 1
              run: echo "Running  on master push"  
              
    on-pull-request: # job 2
        if: github.event_name == 'pull_request'
        runs-on: ubuntu-latest
        steps: # steps to be executed in the job
            - name: "Running on master push" # step 1
              run: echo "Running  on master push" 
    
    on-pull-request-closed:
         if: github.event_name == 'pull_request' &&  github.event_action == 'closed'
         runs-on: ubuntu-latest
         steps:
            - name: "Running on pull request closed"
              run: echo "Running on pull request closed"         
                
    on-workflow-dispatch: # job 3
        if: github.event_name == 'workflow_dispatch'
        runs-on: ubunut-latest
        steps:
            - name: "Running on workflow dispatch"
              run: echo "Running on workflow dispatch"          